// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Popcorn.Infrastructure.Data;

#nullable disable

namespace Popcorn.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227224935_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Popcorn.Domain.Entities.Atleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Equipe")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pontuacao1")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao10")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao11")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao12")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao13")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao14")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao15")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao2")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao3")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao4")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao5")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao6")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao7")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao8")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao9")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoOrganizador")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoParticipacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.CampeonatoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao1")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao10")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao11")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao12")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao13")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao14")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao15")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao2")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao3")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao4")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao5")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao6")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao7")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao8")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao9")
                        .HasColumnType("int");

                    b.Property<bool>("PontuacaoEspecial")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PontuacaoOrganizador")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoParticipacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("EventoId");

                    b.ToTable("CampeonatoEventos");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdadeMax")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeMin")
                        .HasColumnType("int");

                    b.Property<bool>("NaoClassificaGeral")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Chegada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<bool>("FlagDNF")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FlagDNS")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FlagDSQ")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("HoraChegada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Volta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("EventoId");

                    b.ToTable("Chegadas");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ClassificarTempoBruto")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HoraLargada")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Modalidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeMunicip")
                        .HasColumnType("longtext");

                    b.Property<int?>("QtGeral")
                        .HasColumnType("int");

                    b.Property<int?>("QtGeralMunicip")
                        .HasColumnType("int");

                    b.Property<bool>("SepGeralMunicip")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SepararGeral")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.EventoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("EventoTrajetoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HoraLargada")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("NroVoltas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EventoId");

                    b.HasIndex("EventoTrajetoId");

                    b.ToTable("EventoCategorias");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.EventoTrajeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Distancia")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HoraLargada")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantVoltas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("EventoTrajetos");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.InscricaoAtleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("int");

                    b.Property<string>("Camisa")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventoCategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HoraLargada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Organizador")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RetirouKit")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TagRfid")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("EventoCategoriaId");

                    b.HasIndex("EventoId");

                    b.ToTable("InscricoesAtletas");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int?>("PosicaoCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("PosicaoGeral")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TempoBruto")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("TempoLiquido")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("TempoTotal")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("EventoId");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.CampeonatoEvento", b =>
                {
                    b.HasOne("Popcorn.Domain.Entities.Campeonato", "Campeonato")
                        .WithMany("CampeonatoEventos")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Popcorn.Domain.Entities.Evento", "Evento")
                        .WithMany("CampeonatoEventos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Chegada", b =>
                {
                    b.HasOne("Popcorn.Domain.Entities.Atleta", "Atleta")
                        .WithMany("Chegadas")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Popcorn.Domain.Entities.Evento", "Evento")
                        .WithMany("Chegadas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.EventoCategoria", b =>
                {
                    b.HasOne("Popcorn.Domain.Entities.Categoria", "Categoria")
                        .WithMany("EventoCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Popcorn.Domain.Entities.Evento", "Evento")
                        .WithMany("Categorias")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Popcorn.Domain.Entities.EventoTrajeto", "EventoTrajeto")
                        .WithMany("EventoCategorias")
                        .HasForeignKey("EventoTrajetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Evento");

                    b.Navigation("EventoTrajeto");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.EventoTrajeto", b =>
                {
                    b.HasOne("Popcorn.Domain.Entities.Evento", "Evento")
                        .WithMany("Trajetos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.InscricaoAtleta", b =>
                {
                    b.HasOne("Popcorn.Domain.Entities.Atleta", "Atleta")
                        .WithMany("Inscricoes")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Popcorn.Domain.Entities.EventoCategoria", "EventoCategoria")
                        .WithMany("Inscricoes")
                        .HasForeignKey("EventoCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Popcorn.Domain.Entities.Evento", "Evento")
                        .WithMany("Inscricoes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Evento");

                    b.Navigation("EventoCategoria");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Resultado", b =>
                {
                    b.HasOne("Popcorn.Domain.Entities.Atleta", "Atleta")
                        .WithMany("Resultados")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Popcorn.Domain.Entities.Evento", "Evento")
                        .WithMany("Resultados")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Atleta", b =>
                {
                    b.Navigation("Chegadas");

                    b.Navigation("Inscricoes");

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Campeonato", b =>
                {
                    b.Navigation("CampeonatoEventos");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("EventoCategorias");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.Evento", b =>
                {
                    b.Navigation("CampeonatoEventos");

                    b.Navigation("Categorias");

                    b.Navigation("Chegadas");

                    b.Navigation("Inscricoes");

                    b.Navigation("Resultados");

                    b.Navigation("Trajetos");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.EventoCategoria", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("Popcorn.Domain.Entities.EventoTrajeto", b =>
                {
                    b.Navigation("EventoCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
